AIC-220: Large language models compilation of sources
gorillalogic-ai-team/gorilla-logic-ai pull request #2
Opened 2024-01-16 14:17 UTC by reynaldoguerreroGL

[Jira issue id](https://gorillalogic.atlassian.net/browse/AIC-220): Document introducing LLMs basic information

## Changes

Introduction of LLMs basic information.
- Created documentation for [LLMs Basic Information](docs/llms-basic-information.md)

## Important Notes

You can view formatted mark down [here]() or [here]()

2024-01-16 14:22 UTC, reynaldoguerreroGL reviewed
@juandrincon not sure if all of the documentation we want for it to live under a folder named `docs`?

2024-01-16 14:34 UTC, MGorillaLG approved these changes

2024-01-16 14:46 UTC, reynaldoguerreroGL commented
> @juandrincon not sure if all of the documentation we want for it to live under a folder named `docs`?

@juandrincon renamed folder to llms 👍

2024-01-16 15:40 UTC, juandrincon requested changes

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +Given that the purpose of this document is to lay down the key basic concepts of LLM’s, the first question we asked ourselves as newies in this area was, where do we start from? So next thing we did,
basic concepts of **LLM’s** -> Change to **LLMs**. Check if there are more occurrences.

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +Given that the purpose of this document is to lay down the key basic concepts of LLM’s, the first question we asked ourselves as newies in this area was, where do we start from? So next thing we did,
newbies

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +Given that the purpose of this document is to lay down the key basic concepts of LLM’s, the first question we asked ourselves as newies in this area was, where do we start from? So next thing we did,
delete *from*

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +Given that the purpose of this document is to lay down the key basic concepts of LLM’s, the first question we asked ourselves as newies in this area was, where do we start from? So next thing we did,
So *the* next thing we did...

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> + Next step was to Google ourselves around this concept and found that LLMs are also referred to as neural networks (NN) that can perform a variety of natural language processing (NLP), along with ano
*The* next step...

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +
Can we include a brief introductory text here?
Something like:
An LLM is not just a black box transforming inputs into outputs. It has inside several elements allowing...

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +Enables a language model to focus on single parts of the input text that is relevant allowing the model to generate the most accurate outputs.
allowing the model -> allowing it to generate...

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +![](https://lh7-us.googleusercontent.com/mxBnI7fA5XWLyYPd4gfRuY6_LifdvmX3J6bFLQaO9L0XqRbgqnXE_LUwdSbYC_Hmki7h91yGHDldlU0kzd0ZbGbHy0b4g9lJ_KzuzoMRay3b1oORf6Lyf_vMon-r1vf87M79k-nx-fbeHLuFShJVDWU)
What happens if the image URL gets broken? Shouldn't we better download and embed the image? I can imagine them changing the image URL or deleting/editing the blog post, for instance.

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +
Adding a very friendly explanation of the image here would be great. That image is quite difficult to understand, so taking the time to understand and explain it would be amazing.

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +## ![](https://lh7-us.googleusercontent.com/3Pl3EnkvpXYIqWwo0K4M3a8Eo8yklm7BBa3txtQkbxwYYQDttg6S1ndp5yemHAjCN6twkDb1mOpOX0JmrB5Q_SArMsIw6HymhfiriSVGshl8jzrhB5uGPuI3EyCA0cqn-vU0RxB4M8Yk8sxSC_7lJTQ)Art
Same comment about the image URL.

And let's take the opportunity to delete from it the '+', the '.' and the colored line above the image. Look weird.

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +
A brief introductory text here would be helpful. Something like:

LLMs didn't come out of a magician's hat. On the contrary, they result from decades of research on cutting-edge technologies. Below, we'll briefly discuss the relationship between concepts such as Artificial Intelligence, Machine Learning, or Deep Learning.

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +## ![](https://lh7-us.googleusercontent.com/3Pl3EnkvpXYIqWwo0K4M3a8Eo8yklm7BBa3txtQkbxwYYQDttg6S1ndp5yemHAjCN6twkDb1mOpOX0JmrB5Q_SArMsIw6HymhfiriSVGshl8jzrhB5uGPuI3EyCA0cqn-vU0RxB4M8Yk8sxSC_7lJTQ)Art
Shouldn't we add a line break here? Between the image and the title.

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +## ![](https://lh7-us.googleusercontent.com/3Pl3EnkvpXYIqWwo0K4M3a8Eo8yklm7BBa3txtQkbxwYYQDttg6S1ndp5yemHAjCN6twkDb1mOpOX0JmrB5Q_SArMsIw6HymhfiriSVGshl8jzrhB5uGPuI3EyCA0cqn-vU0RxB4M8Yk8sxSC_7lJTQ)Art
*Generate AI* doesn't exist, I think.

It would be *Generative AI*. Even so, I wouldn't put them on the same level. Generative AI would be exactly the same circle as the LLM one on the image.
. AI
   . ML
      . DL
         . GenAI

So just delete **and Generate AI** of this heading

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +We have to start first by understanding what is Artificial Intelligence, long story short we can define it as the simulation of human intelligence process by computer systems and it has a wide variet
I would prefere *computer vision*, instead of *machine vision*

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +On the other hand, Generative AI refers to a type of artificial intelligence that can produce various types of content. Its popularity resides in the simplicity of new user interfaces that permit the
Again, the concepts here are mixed. And they continue mixed until the *Neural Networks* section.
AI is one concept, ML is another, DL is another (and it includes Neural Networks), and Generative AI is another (and it includes LLMs).

So my proposal would be:
1. Organize the sections as follows: Artificial Intelligence, Machine Learning, Deep Learning, and Generative AI.
2. Move "On the other hand, Generative AI refers to a type of artificial intelligence that can produce various types of content..." to the Generative AI section.
3. Rebuild (from scratch) the ML and the DL sections.

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +LLMs uses 3 things: data, architecture and training ([resource](https://www.youtube.com/watch?v=5sLYAQS9sWQ)).
An LLM uses 3 things...

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +The data is the input that uses our LLM that could be tons of information in text format. Architecture is strongly related with the neural network that’s being used, it enables the model to handle se
Check this paragraph's wording. Looks weird.
"The data is the input that uses our LLM that could be..." ??????

Seems you were tired when reached this point 😆

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +# LLMs applicability<a id="llms-applicability"></a>
Capitalize "Applicability" to continue the same format of the other section titles.

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +Areas like content creating is another that’s really popular with LLMs which can use text or image inputs to create refined content like images, videos, audio or even text to help content creators, f
content *creation*

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +Software development is an area that has been upgraded with the integration of tools like code assistant and LLMs that can transform simple sentences or images in code or basic applications, decreasi
like *coding assistants*
delete "and LLMs"

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +# LLMs Advantages and disadvantages<a id="llms-advantages-and-disadvantages"></a>
Capitalize *Disadvantages* to follow format of other section titles.

2024-01-16 15:40 UTC, juandrincon commented on llms/llms-basic-information.md
> +# What are large language models (LLMs)?<a id="what-are-large-language-models-llms"></a>
As this file doesn't try to explain LLMs in detail but to give the user a set of resources, my first line would be a note saying that. Something like

> [!NOTE]
> There are already thousands of resources explaining clearly and down to the last detail of Generative AI and how an LLM works. This document aims to give the reader a brief summary of some crucial topics and a set of resources they can access to extend their lecture.

2024-01-16 17:02 UTC, reynaldoguerreroGL reviewed
First set of changes are done and I've marked as resolved accordingly so you can review @juandrincon, I will proceed with second set of changes shortly.

2024-01-16 17:02 UTC, reynaldoguerreroGL commented on llms/llms-basic-information.md
> +There are already thousands of resources explaining clearly and down to the last detail Generative AI and how an LLM works. This document aims to give the reader a brief summary of some crucial topic
Done https://github.com/gorillalogic-ai-team/gorilla-logic-ai/pull/2/files#diff-00fdd73d557f981c84caeb824a900e79fa999a5b4b632c2e1a8e09ceba421b72R1-R2
Looks weird [here](https://github.com/gorillalogic-ai-team/gorilla-logic-ai/pull/2/files?short_path=00fdd73#) but seems like the final rendered document looks good [here](https://github.com/gorillalogic-ai-team/gorilla-logic-ai/blob/d9c30a93e0f75770063b9bd71b5f64d070a9eb46/llms/llms-basic-information.md)

2024-01-16 18:38 UTC, reynaldoguerreroGL reviewed
@juandrincon a second set of changes has been done and marked as resolved accordingly, please review and let me know of any further changes.

2024-01-16 18:38 UTC, reynaldoguerreroGL commented on llms/llms-basic-information.md
> +## ![](https://lh7-us.googleusercontent.com/3Pl3EnkvpXYIqWwo0K4M3a8Eo8yklm7BBa3txtQkbxwYYQDttg6S1ndp5yemHAjCN6twkDb1mOpOX0JmrB5Q_SArMsIw6HymhfiriSVGshl8jzrhB5uGPuI3EyCA0cqn-vU0RxB4M8Yk8sxSC_7lJTQ)Art
Done here [llms/images/ai-ml-dl-generative-ai.webp](https://github.com/gorillalogic-ai-team/gorilla-logic-ai/pull/2/files#diff-c08f2e2acd835d6f37c385ec7f67dbd8ee48b11d265f87b80e1cd9cd90ae9b98) and here https://github.com/gorillalogic-ai-team/gorilla-logic-ai/pull/2/files#diff-00fdd73d557f981c84caeb824a900e79fa999a5b4b632c2e1a8e09ceba421b72R55

2024-01-16 19:27 UTC, juandrincon submitted a review, later dismissed

2024-01-16 21:53 UTC, juanvalverdeGL reviewed
Great work 🤘

2024-01-17 15:19 UTC, reynaldoguerreroGL commented on llms/llms-basic-information.md
> +![transformer-model](./images/transformer-model.png)
Done in https://github.com/gorillalogic-ai-team/gorilla-logic-ai/pull/2/commits/04da9b90ae1b98f93831cfeca06047ca6fd4fe62 and in https://github.com/gorillalogic-ai-team/gorilla-logic-ai/pull/2/commits/cb78687550dd8090363c49d53f1c421d5e973526

2024-01-17 15:19 UTC, reynaldoguerreroGL commented on llms/llms-basic-information.md
> +### The embedding layer <a id="the-embedding-layer"></a>
Done in https://github.com/gorillalogic-ai-team/gorilla-logic-ai/pull/2/commits/04da9b90ae1b98f93831cfeca06047ca6fd4fe62

2024-01-17 15:20 UTC, reynaldoguerreroGL reviewed
@juanvalverdeGL your suggestions have been addresses and I've marked them as resolved accordingly, please review and let me know of any other changes you consider pertinent.

2024-01-17 15:56 UTC, juandrincon commented on llms/llms-basic-information.md
> +![ai-ml-dl-generative-ai](./images/ai-ml-dl-generative-ai.webp)
I like this image very much. A 🤏 change. Can we make it smaller? When you open the document, it looks huge, calling so much of your attention. 

Everything else approved from my side

2024-01-17 16:05 UTC, reynaldoguerreroGL commented on llms/llms-basic-information.md
> +![ai-ml-dl-generative-ai](./images/ai-ml-dl-generative-ai.webp)
Sure thing, how about [now](https://github.com/gorillalogic-ai-team/gorilla-logic-ai/blob/6652762c166ed990bfa90feac2929e2e13a76247/llms/llms-basic-information.md), with the same width as image `transformer-model.png`

2024-01-17 16:06 UTC, juandrincon approved these changes

2024-01-17 18:09 UTC, juanvalverdeGL approved these changes

2024-01-17 18:22 UTC, merged