Add 'Good Practices for Using GitHub Copilot' section
gorillalogic-ai-team/gorilla-logic-ai pull request #3
Opened 2024-01-16 15:54 UTC by sebastiancastano1

## Changes

1. Added 'Good Practices for Using GitHub Copilot' section to README.
2. Included a Mermaid diagram for the GitHub Copilot Code Review Process.
3. Outlined key practices: understand, review, and test suggestions; use comments; be aware of licensing.

## important notes

I am open to suggestions. This is a preliminary work that can be modified.

![Screenshot 2024-01-16 at 10 53 33 AM](https://github.com/gorillalogic-ai-team/gorilla-logic-ai/assets/97634093/d95a6b45-0718-4694-ae2b-1d4dd6051b9a)

2024-01-16 16:33 UTC, juandrincon commented on .github/coding-assistants/README.md
> +Developer-->>Copilot: Requests more suggestions or modifications
Use the base form of the verbs to make the diagram consistent. You used 'Write' and 'Provide'. So use 'Request', 'Provide', and 'Continue' in the next lines.

2024-01-16 16:33 UTC, juandrincon commented on .github/coding-assistants/README.md
> +# Good practices for using GitHub Copilot
It's a great document, team. Congrats.
The only main change I suggest is to add an introductory paragraph. Something like:
1. Change the title to "AI Coding Assistants"
2. Add an introductory paragraph here. You can use some info from [the article we wrote](https://docs.google.com/document/d/17p5CkPucGvo7YSYJUDqCfeWasH6GrBQTXOsqyFWFbhw/edit?usp=sharing), such as the example I'll add at the end of this comment.
3. Refer to the white paper we are finishing (we can add the [Drive link](https://docs.google.com/document/d/17p5CkPucGvo7YSYJUDqCfeWasH6GrBQTXOsqyFWFbhw/edit?usp=sharing) now, but we must change it to the blog once it's been released).
4. Make 'Good practices for using GitHub Copilot' an H2. Then the subsections H3, and so on.

That way, we can use this document like the introductory one about AI coding assistants.

Sample intro paragraph:

In 2022, OpenAI launched ChatGPT, an LLM–based chatbot that has gained the entire attention of the AI community. It has demonstrated the power of GenAI to change how we develop software. Additionally, models like Codex, CodeBERT, PaLM, and AlphaCode have been trained on millions of lines of code. Nowadays, they are the heart of AI coding assistants such as Github Copilot, Amazon CodeWhisperer, and Tabnine. These tools are widely used for code generation, completion, translation, repair, summarization, and explanation, among other use cases.

2024-01-16 19:14 UTC, sebastiancastano1 commented on .github/coding-assistants/README.md
> +Developer-->>Copilot: Requests more suggestions or modifications
Done

2024-01-16 19:14 UTC, sebastiancastano1 commented on .github/coding-assistants/README.md
> +# Good practices for using GitHub Copilot
Done

2024-01-16 19:21 UTC, juandrincon submitted a review, later dismissed

2024-01-16 19:21 UTC, juandrincon commented on .github/coding-assistants/README.md
> +In 2022, OpenAI unveiled ChatGPT, an LLM-based chatbot, capturing the AI community's spotlight and showcasing GenAI's transformative potential in software development1. Further advancements include m
Delete the '1' after software development1.

2024-01-16 19:21 UTC, juandrincon commented on .github/coding-assistants/README.md
> +Read more about these advancements in the research paper [link to the paper](https://docs.google.com/document/d/17p5CkPucGvo7YSYJUDqCfeWasH6GrBQTXOsqyFWFbhw/edit?usp=sharing).
Change [link to the paper] for [available here]

2024-01-16 19:41 UTC, sebastiancastano1 commented on .github/coding-assistants/README.md
> +In 2022, OpenAI unveiled ChatGPT, an LLM-based chatbot, capturing the AI community's spotlight and showcasing GenAI's transformative potential in software development1. Further advancements include m
Done

2024-01-16 19:41 UTC, sebastiancastano1 commented on .github/coding-assistants/README.md
> +Read more about these advancements in the research paper [link to the paper](https://docs.google.com/document/d/17p5CkPucGvo7YSYJUDqCfeWasH6GrBQTXOsqyFWFbhw/edit?usp=sharing).
Done

2024-01-16 19:52 UTC, juandrincon approved these changes

2024-01-16 20:34 UTC, reynaldoguerreroGL reviewed
@sebastiancastano1 I've added a comment that may or may not make sense, for your review.

2024-01-16 20:34 UTC, reynaldoguerreroGL commented on .github/coding-assistants/README.md
> +Read more about these advancements in the research paper [available here](https://docs.google.com/document/d/17p5CkPucGvo7YSYJUDqCfeWasH6GrBQTXOsqyFWFbhw/edit?usp=sharing).
Given that this is the public repo, and it is pointing to a document which is in Gorilla's drive, maybe not all of the public will have access to it, hence it would make sense to export it as a PDF and make it part of this repo and reference it here with a relative path? Example:
```
... [available here](../../documents/AI-Assisted-Software-Development.pdf)
```
the above relative path assuming that we want to have a main folder `documents` for this purpose?

2024-01-16 20:51 UTC, juanvalverdeGL requested changes

2024-01-16 20:51 UTC, juanvalverdeGL commented on .github/coding-assistants/README.md
> +In 2022, OpenAI unveiled ChatGPT, an LLM-based chatbot, capturing the AI community's spotlight and showcasing GenAI's transformative potential in software development. Further advancements include mo
Too many commas at the beginning. How about : "In 2022 OpenAI unveiled ChatGPT, an LLM-based chatbot, capturing the AI community's ... "

2024-01-16 20:51 UTC, juanvalverdeGL commented on .github/coding-assistants/README.md
> +# AI Coding Assistants
Why is this file and new dir under ".github" ?

2024-01-16 20:51 UTC, juanvalverdeGL commented on .github/coding-assistants/README.md
> +```mermaid
Diagram looks great. Should we include a stage early in the game when the developer "provides context", either through comments or open tabs? That's very important. Also the final accepted result comes after 3+ iterations or improvements on the first output. That could also be indicated.

2024-01-16 20:51 UTC, juanvalverdeGL commented on .github/coding-assistants/README.md
> +
Should we add section title, such as "Recommendations" or "Best practices" ?

2024-01-16 21:06 UTC, juandrincon commented on .github/coding-assistants/README.md
> +# AI Coding Assistants
Nice catch 😅

2024-01-16 21:09 UTC, sebastiancastano1 commented on .github/coding-assistants/README.md
> +# AI Coding Assistants
Nice catch 😮‍💨

2024-01-16 21:16 UTC, sebastiancastano1 commented on .github/coding-assistants/README.md
> +Read more about these advancements in the research paper [available here](https://docs.google.com/document/d/17p5CkPucGvo7YSYJUDqCfeWasH6GrBQTXOsqyFWFbhw/edit?usp=sharing).
If the document is ready, we can use the PDF approach. @juandrincon

2024-01-16 21:20 UTC, juandrincon commented on .github/coding-assistants/README.md
> +Read more about these advancements in the research paper [available here](https://docs.google.com/document/d/17p5CkPucGvo7YSYJUDqCfeWasH6GrBQTXOsqyFWFbhw/edit?usp=sharing).
Thinking about it better, we can just add a note.
1. If we put the PDF it can quickly get deprecated. Furthermore, I'm working on the V2.
2. If we leave the Drive URL, it makes the document inaccessible to anyone outside the company. It will be released in our blog soon.

> [!NOTE]
> We are working on a white paper introducing the basis of AI coding assistants. We'll publish the link here as soon as it's been released.

2024-01-16 21:28 UTC, sebastiancastano1 commented on .github/coding-assistants/README.md
> +In 2022, OpenAI unveiled ChatGPT, an LLM-based chatbot, capturing the AI community's spotlight and showcasing GenAI's transformative potential in software development. Further advancements include mo
As you mentioned, I can remove the first comma, but I wonder if having multiple commas is a bad styling pattern.

2024-01-16 21:49 UTC, sebastiancastano1 commented on .github/coding-assistants/README.md
> +Read more about these advancements in the research paper [available here](https://docs.google.com/document/d/17p5CkPucGvo7YSYJUDqCfeWasH6GrBQTXOsqyFWFbhw/edit?usp=sharing).
Done

2024-01-16 21:49 UTC, sebastiancastano1 commented on .github/coding-assistants/README.md
> +In 2022, OpenAI unveiled ChatGPT, an LLM-based chatbot, capturing the AI community's spotlight and showcasing GenAI's transformative potential in software development. Further advancements include mo
Done

2024-01-16 21:49 UTC, sebastiancastano1 commented on .github/coding-assistants/README.md
> +# AI Coding Assistants
Done, and thanks again 🙇

2024-01-16 21:49 UTC, sebastiancastano1 commented on .github/coding-assistants/README.md
> +```mermaid
Done

2024-01-16 21:49 UTC, sebastiancastano1 commented on .github/coding-assistants/README.md
> +
Done

2024-01-16 21:59 UTC, juanvalverdeGL submitted a review, later dismissed
🍻

2024-01-16 22:03 UTC, reynaldoguerreroGL commented on .github/coding-assistants/README.md
> +Read more about these advancements in the research paper [available here](https://docs.google.com/document/d/17p5CkPucGvo7YSYJUDqCfeWasH6GrBQTXOsqyFWFbhw/edit?usp=sharing).
@sebastiancastano1 just so we standarize our `Notes` in our Markdowns, does it make sense to you to make it as in https://github.com/gorillalogic-ai-team/gorilla-logic-ai/blob/2ee7387cd1e1510a56942f413f423a2cd0ffbde3/llms/llms-basic-information.md ?

2024-01-16 22:09 UTC, juandrincon commented on .github/coding-assistants/README.md
> +Read more about these advancements in the research paper [available here](https://docs.google.com/document/d/17p5CkPucGvo7YSYJUDqCfeWasH6GrBQTXOsqyFWFbhw/edit?usp=sharing).
+1. I wrote you the code in my comment, Sebas.

```
> [!NOTE]
>
```

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

2024-01-17 19:22 UTC, reynaldoguerreroGL approved these changes
LGTM

2024-01-17 19:44 UTC, juandrincon approved these changes

2024-01-17 20:09 UTC, juanvalverdeGL approved these changes

2024-01-17 20:21 UTC, merged